---
title: "Assignment 3 Task 1"
author: "Justine Lang"
date: "2023-03-02"
output: 
  html_document: 
    code_folding: hide
---

```{r setup, include=FALSE, echo = TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(ggfortify)
```

## Data Overview

Explain data and variables

```{r}
### Read in the data

env_vars <- read_csv(here("data", "world_env_vars.csv"))
```


## Data Wrangling

Explain methods

```{r}
### Drop NA's, clean names, and set levels for accessibility_to_cities

env_vars <- env_vars %>%
  clean_names() %>%
  drop_na() %>% 
  mutate(accessibility_to_cities =
                     case_when(accessibility_to_cities <= 100 ~ "Very High", 
                              accessibility_to_cities <= 500 ~ "High",
                              accessibility_to_cities <= 1000 ~ "Medium",
                              accessibility_to_cities <= 11000 ~ "Low")) %>% 
  mutate(accessibility_to_cities = factor(accessibility_to_cities, levels = c('Low', 'Medium', 'High', 'Very High')))

# glimpse(env_vars)
```

```{r}
### Select variables of interest and scale

env_vars_pca <- env_vars %>%
  select(cropland_cover, tree_canopy_cover, rain_mean_annual, temp_mean_annual, temp_annual_range, wind, cloudiness) %>% 
  dplyr::select(where(is.numeric)) %>%
  scale() %>%
  prcomp()

### See the loadings

 # env_vars_pca$rotation
```


## Biplot

```{r}
### add caption

autoplot(env_vars_pca,
     	data = env_vars,
     	loadings = TRUE,
     	colour = 'accessibility_to_cities',
     	loadings.label = TRUE,
     	loadings.colour = "black",
     	loadings.label.colour = "black",
     	loadings.label.vjust = -0.5
     	) +
  scale_color_manual(values = c('red', 'orange', 'yellowgreen', 'darkgreen')) +
  scale_fill_manual(values = c('red', 'orange', 'yellowgreen', 'darkgreen')) +
  theme_minimal()
```


## Screeplot

```{r}
### add caption

sd_vec <- env_vars_pca$sdev
var_vec <- sd_vec^2 ### standard deviation is sqrt of variance!
pc_names <- colnames(env_vars_pca$rotation)
pct_expl_df <- data.frame(v = var_vec,
                          pct_v = var_vec / sum(var_vec),
                          pc = fct_inorder(pc_names)) %>%
  mutate(pct_lbl = paste0(round(pct_v*100, 1), '%'))
ggplot(pct_expl_df, aes(x = pc, y = v)) +
  geom_col(color = "navyblue", fill = "lightblue") +
  ggtitle("Screeplot for World Environmental Variables")+
  geom_text(aes(label = pct_lbl), vjust = 0, nudge_y = .002) +
  labs(x = 'Principal component', y = 'Variance explained')+
  theme_minimal()
```


## Summary

Main points here. 


## Citation

Data citation here. 








